export const MOVIE_VOTE_LIKE_REQUEST = "MOVIE_VOTE_LIKE_REQUEST";
export const MOVIE_VOTE_LIKE_SUCCESS = "MOVIE_VOTE_LIKE_SUCCESS";
export const MOVIE_VOTE_LIKE_FAIL = "MOVIE_VOTE_LIKE_FAIL";

export const MOVIE_VOTE_DISLIKE_REQUEST = "MOVIE_VOTE_DISLIKE_REQUEST";
export const MOVIE_VOTE_DISLIKE_SUCCESS = "MOVIE_VOTE_DISLIKE_SUCCESS";
export const MOVIE_VOTE_DISLIKE_FAIL = "MOVIE_VOTE_DISLIKE_FAIL";
